### ISSUE TITLE
[miniLLM] how to use lora training when the model mp_size > 1

### ISSUE THREAD

**Issue by cailinhang** [microsoft/LMOps#105]
Sorry to bother you guys again.

With the lora script, I can use lora to speed up the training of llama-7b and llama-13b if I do not use `model parallel`  and `MP=4` arugument ).  The training is much faster with lora.

However, the peft  library cannot be directly applied to The `ParallelLlamaForCausalLM`  class because some subclasses used by  `ParallelLlamaForCausalLM`  is not supported by peft.

The following is the error message if I apply peft when I set  `model parallel`  and `MP=4` arugument.
```
ValueError: Target module ColumnParallelLinear() is not supported. 
Currently, only `torch.nn.Linear` and `Conv1D` are supported.
```
However, when I try to use `scripts/llama/minillm/train_7B_13B_lora.sh ` to use the `minillm` method on 2 x 8 v100 gpus.  The student model llama-7b and  teacher llama-13b are both trained by lora.  I got Out of Memory error because by default `model parallel`   is not used. So I guess MP > 1 is needed.

**Comment by t1101675** [comment]
The error is because we use LoRA in `peft` package, which has not supported model parallel yet. Supporting this needs re-implementing LoRA in `transformers` by ourselves and is not part of the recent plan. Contributions are welcome!

**Comment by cailinhang** [comment]
> The error is because we use LoRA in `peft` package, which has not supported model parallel yet. Supporting this needs re-implementing LoRA in `transformers` by ourselves and is not part of the recent plan. Contributions are welcome!

Thanks for reply. 
* I temporarily bypass this issue by merging the `lora` weight with the base weight of llama-7b and llama-13b.  
* Then I use `convert_mp.py` to convert them to `MP=4` to avoid OOM.
* Then I use `minillm` method as before without lora.
