### ISSUE TITLE
when I run the hf-version on the fairseq-dense-125M ,there is error ""TypeError: forward() got an unexpected keyword argument 'prefix_parallel'

### ISSUE THREAD

**Issue by 2018211801** [microsoft/LMOps#11]
when I run the hf-version on the fairseq-dense-125M ,there is error ""model has no attribution of parralel"",when I remove the param --parallel, there is another error  ""TypeError: forward() got an unexpected keyword argument 'prefix_parallel'.

**Comment by 2018211801** [comment]
the first error is AttributeError: 'XGLMForCausalLM' object has no attribute 'parallelize'

**Comment by donglixp** [comment]
@2018211801  Could you also post the command?
