### ISSUE TITLE
MiniLLM: BOS token is missing in training, but present during evaluation

### ISSUE THREAD

**Issue by artsobolev** [microsoft/LMOps#123]
As the title says, the `bos_token_id` is omitted during dataset preprocessing ([process_data_dolly.py#L40](https://github.com/microsoft/LMOps/blob/main/minillm/tools/process_data_dolly.py#L40) has `add_special_tokens=False`), but is not removed during evaluation ([prompt_datasets.py#L66](https://github.com/microsoft/LMOps/blob/main/minillm/data_utils/prompt_datasets.py#L66), for example, lacks `add_special_tokens`).

Indeed, datapoints from the prerocessed dolly dataset you've provided have no tokens `1`, however, input_ids tensors in the eval script do have it.

So which one is the correct way to use the model?

**Comment by AInkCode** [comment]
How do you download the dolly dataset? Can you give me the URL and the steps? Thanks~

**Comment by AInkCode** [comment]
@artsobolev How do you download the dolly dataset? Can you give me the URL and the steps? Thanks~

**Comment by t1101675** [comment]
There is indeed a mismatch between training and evaluation. Thanks for pointing it out!
The best way to use the model is inference without the token `1` to match the model training.  However we have compared the two cases in the evaluation and found that the results do not change much.
For LLaMA on Dolly:
|                  | With `1`      | Without `1` |
| ----------- | ----------- | ----------- |
| SFT w/o KD | 26.3        | 26.5       |
| KD               | 27.4        | 27.2        |
| SeqKD         | 27.5        | 27.6        |
| MiniLLM      | 29.0        | 29.1        |
