### ISSUE TITLE
The file name is missing l

### ISSUE THREAD

**Issue by ycp1027** [microsoft/LMOps#147]
![微信图片_20231231142844](https://github.com/microsoft/LMOps/assets/52107305/ab3d5e5b-a40d-4e06-8986-8d488f54c866)

**Comment by SleepEarlyLiveLong** [comment]
Sorry, I will fix it later today

**Comment by donglixp** [comment]
https://github.com/microsoft/LMOps/commit/e12e572665c8deb6b4ac3d452ea8a68fb0af0ffa
