### ISSUE TITLE
Paper：ADAPTING LARGE LANGUAGE MODELS VIA READING COMPREHENSION 

### ISSUE THREAD

**Issue by J-G-Y** [microsoft/LMOps#149]
Hello, I'm a student who has just entered the NLP industry. I'd like to ask you about the technical details of this article's title. After you constructed the data, did you continue with the NEXT TOKEN PREDICT Task on the original model? Or did you use the QA data for supervised fine-tuning to achieve domain adaptation? 
Looking forward to your response.

**Comment by cdxeve** [comment]
Hi, after constructing the data, we DID continue with the standard NEXT TOKEN PREDICT Task on the original model.

**Comment by cdxeve** [comment]
Hi, I think PEFT methods should be effective, as our approach can be seen as a form of supervised fine-tuning. Just make sure to compute the NEXT TOKEN PREDICT Task loss on all the tokens.
