### ISSUE TITLE
[MiniLLM] sft of llama2-7b out of memory on V100

### ISSUE THREAD

**Issue by yumath** [microsoft/LMOps#160]
I use 1 node 4 V100（32G） to sft on llama2-7b, script: `minillm/scripts/llama2/sft/sft_7B.sh`, but got out of memory error. Should I using a more larger GPU? or I have something wrong? (because https://github.com/microsoft/LMOps/issues/91 is trained on V100)

**Comment by t1101675** [comment]
Training llama2-7b requires at least 16x 32G V100 (#91 is trained with 16 32G V100)

**Comment by yumath** [comment]
Thanks for your reply!
