### ISSUE TITLE
[MiniLLM]Why dolly only has 12435 training samples?

### ISSUE THREAD

**Issue by yumath** [microsoft/LMOps#168]
but in your paper, Section 3.1 

> Training
We construct the training data from databricks-dolly-15k consisting of 15K human-
written instruction-response pairs. We randomly split **14K samples** as the training set D and left
500 samples for validation and testing, respectively.

**Comment by t1101675** [comment]
See #167

**Comment by t1101675** [comment]
See #167

**Comment by yumath** [comment]
Thx very much
