### ISSUE TITLE
ImportError: cannot import name 'mpu' from 'transformers'

### ISSUE THREAD

**Issue by qxpBlog** [microsoft/LMOps#176]
@artsobolev @donglixp @intfloat @wolfshow when i run the scripts``` bash /home//LMOps-main/minillm/scripts/llama2/sft/sft_7B.sh  ```, this problem happend. My transformers version is 4.38.2. How can i solve it?

**Comment by qxpBlog** [comment]
> You should use the transformers provided in our repo by `pip3 install -e transformers/`

Thank you for your answer.I have another question:How can I specify the GPU number during code execution when i run the script ```bash /home//LMOps-main/minillm/scripts/llama2/sft/sft_7B.sh  ```

**Comment by t1101675** [comment]
This [line](https://github.com/microsoft/LMOps/blob/aa2b4680c60108d46101b3fb1eeff90f0f94e2d6/minillm/scripts/llama2/sft/sft_7B.sh#L7) controls the GPU number.

**Comment by qxpBlog** [comment]
> This [line](https://github.com/microsoft/LMOps/blob/aa2b4680c60108d46101b3fb1eeff90f0f94e2d6/minillm/scripts/llama2/sft/sft_7B.sh#L7) controls the GPU number.

thanks, I have got it.
