### ISSUE TITLE
Questions about task datasets used in the paper "Adapt LLM to domains"

### ISSUE THREAD

**Issue by Lydia-yang** [microsoft/LMOps#182]
Hi, thanks for your great job. I am following your work and have a question about the dataset. Since I found that only test data are released, could you please release all the task datasets (including training and test data) used in fine-tuning?

**Comment by cdxeve** [comment]
Hi, thanks for your interest in our work, we will release the datasets on huggingface within this week.

**Comment by cdxeve** [comment]
Hi, the datasets are available on huggingface now:

- [ChemProt](https://huggingface.co/datasets/AdaptLLM/ChemProt)
- [RCT](https://huggingface.co/datasets/AdaptLLM/RCT)
- [ConvFinQA](https://huggingface.co/datasets/AdaptLLM/ConvFinQA)
- [FiQA_SA](https://huggingface.co/datasets/AdaptLLM/FiQA_SA)
- [Headline](https://huggingface.co/datasets/AdaptLLM/Headline)
- [NER](https://huggingface.co/datasets/AdaptLLM/NER)

The other datasets used in our paper have already been available in huggingface, so you can directly load them with the following code
```python
from datasets import load_dataset

# MQP:
dataset = load_dataset('medical_questions_pairs')

# PubmedQA:
dataset = load_dataset('bigbio/pubmed_qa')

# SCOTUS
dataset = load_dataset("lex_glue", 'scotus')

# CaseHOLD
dataset = load_dataset("lex_glue", 'case_hold')

# UNFAIR-ToS
dataset = load_dataset("lex_glue", 'unfair_tos')
```
