### ISSUE TITLE
Directory of "structured_prompting/fairseq-version/fairseq" is not installable.

### ISSUE THREAD

**Issue by zhaoguangxiang** [microsoft/LMOps#19]
A bug of 
"structured_prompting/fairseq-version/fairseq does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found." accused when I run 
"pip install --user -e fairseq/"

**Comment by YRdddream** [comment]
Hi, there is 'setup.py' in the directory.
![image](https://user-images.githubusercontent.com/26793787/230913590-ccc5521f-6ca1-4606-954e-bec449385d6e.png)
