### ISSUE TITLE
forward() got an unexpected keyword argument `token_type_ids`

### ISSUE THREAD

**Issue by knightron0** [microsoft/LMOps#208]
I'm trying to run MiniLLM with Llama-2-7b as the teacher model and gpt-2 large as the student model. Not sure why this error is persisting -- my arguments passed into forward() in the `PPOModel` class do not contain token_type_id and I have included `return_token_type_ids=False` with the AutoTokenizer class. 

All related issues I found online told me to upgrade the transformers version, but that doesn't seem to work because `ParallelLlamaForCausalLM` is implemented locally.

**Comment by knightron0** [comment]
Nevermind, I just realized the tokenizer mismatch won't work :P

**Comment by harmya** [comment]
L honestly
