### ISSUE TITLE
How to define the action space in RL?

### ISSUE THREAD

**Issue by junyongyou** [microsoft/LMOps#21]
Is it possible to share the actions in the RL? For example, how to make variation of the prompt in order to improve the aesthetic score? Thank you very much.

**Comment by YRdddream** [comment]
Hi, I don't quite understand your question. Could you be more specific? Like what the action sharing means.

**Comment by junyongyou** [comment]
Hi, Thanks for your reply. What I meant is some technical details in the RL modelling, which are not explained in the paper. For example, what actions are used in the RL process? E.g., in this paper (https://openreview.net/pdf?id=gSHyqBijPFO), the authors have defined some editing techniques to modify the prompts (e.g., Instruction, example, verbalizer in Table in in the paper). If possible, could you please tell about how to modify the prompts to improve the aesthetic scores of the generated images? Thanks a lot.

**Comment by YRdddream** [comment]
Hi, thanks for clarifying. We treat the prompt optimization as a text generation problem. The action space of our model is defined on the whole vocabulary without any constraints. We let the model explore the better prompts freely. It is likely that the model has learned some editing rules implicitly through supervised fine-tuning, but it is totally an automatic process without any pre-defined editing techs.
