### ISSUE TITLE
bash install.sh的时候出错

### ISSUE THREAD

**Issue by zhouchang123** [microsoft/LMOps#210]
Processing /data/zc/uprise/uprise/DPR
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      /data/zc/anaconda/envs/uprise/lib/python3.10/site-packages/setuptools/__init__.py:81: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
        dist.fetch_build_eggs(dist.setup_requires)
      error: Multiple top-level packages discovered in a flat-layout: ['dpr', 'conf'].

      To avoid accidental inclusion of unwanted files or directories,
      setuptools will not proceed with this build.

      If you are trying to create a single distribution with multiple packages
      on purpose, you should not rely on automatic discovery.
      Instead, consider the following options:

      1. set up custom discovery (`find` directive with `include` or `exclude`)
      2. use a `src-layout`
      3. explicitly set `py_modules` or `packages` with a list of names

      To find more information, look for "package discovery" on setuptools docs.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
/data/zc/anaconda/envs/uprise/bin/python: No module named spacy

**Comment by cdxeve** [comment]
Hi, how about first installing spacy: [https://stackoverflow.com/questions/47295316/importerror-no-module-named-spacy-en](https://stackoverflow.com/questions/47295316/importerror-no-module-named-spacy-en)
```bash
pip install spacy
python -m spacy download en
```
and the re-run the install.sh:
```bash
bash install.sh
```

**Comment by zhouchang123** [comment]
What is the python version?
My environment is 3.10。

**Comment by zhouchang123** [comment]
Maybe the version doesn't match.

**Comment by zhouchang123** [comment]
With the problem given originally,I could install other packages successfully,
However,some problem still occur:
 Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      /data/zc/anaconda/envs/uprise/lib/python3.8/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
        dist.fetch_build_eggs(dist.setup_requires)
      error: Multiple top-level packages discovered in a flat-layout: ['dpr', 'conf'].

      To avoid accidental inclusion of unwanted files or directories,
      setuptools will not proceed with this build.

      If you are trying to create a single distribution with multiple packages
      on purpose, you should not rely on automatic discovery.
      Instead, consider the following options:

      1. set up custom discovery (`find` directive with `include` or `exclude`)
      2. use a `src-layout`
      3. explicitly set `py_modules` or `packages` with a list of names

      To find more information, look for "package discovery" on setuptools docs.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by zhouchang123** [comment]
It seems that setup.py lose order 
py_modules=[],
after put in the error is solved.
