### ISSUE TITLE
[MiniLLM] Processed RoBERTa Corpus dataset download

### ISSUE THREAD

**Issue by AKaubay** [microsoft/LMOps#211]
Unable to download processed RoBERTa Corpus only.
Also encountering repeated interruptions during download of the full processed_data.tar with an error indicating dead links, possibly due to incomplete or corrupt file structure in the compressed archive. 
I also tried to download it from my personal computer with a 10 Mbps connection and still encountered the same problem.
![error 1](https://github.com/microsoft/LMOps/assets/162434020/b541139e-f96d-4abe-984b-7b765b231187)
![error 2](https://github.com/microsoft/LMOps/assets/162434020/bc87c75d-05be-4f60-83da-34c86f683ff2)

**Comment by t1101675** [comment]
It works fine in our environment. Is the download started by running the following commands?
```bash
DLINK=$(echo -n "aHR0cHM6Ly9jb252ZXJzYXRpb25odWIuYmxvYi5jb3JlLndpbmRvd3MubmV0L2JlaXQtc2hhcmUtcHVibGljL01pbmlMTE0vcHJvY2Vzc2VkX2RhdGEudGFyP3N2PTIwMjMtMDEtMDMmc3Q9MjAyNC0wNC0xMFQxMyUzQTExJTNBNDRaJnNlPTIwNTAtMDQtMTFUMTMlM0ExMSUzQTAwWiZzcj1jJnNwPXImc2lnPTRjWEpJalZSWkhJQldxSGpQZ0RuJTJGMDFvY3pwRFdYaXBtUENVazNaOHZiUSUzRA==" | base64 --decode)
wget -O processed_data.tar $DLINK
```

**Comment by donglixp** [comment]
https://github.com/microsoft/LMOps/blob/main/minillm/README.md

The links have been updated.
