### ISSUE TITLE
[AdaptLLM] How to evaluate the models' performance?

### ISSUE THREAD

**Issue by yiyiwwang** [microsoft/LMOps#223]
Dear authors, I'm reading your paper [Adapting Large Language Models via Reading Comprehension](https://huggingface.co/papers/2309.09530). I have some questions to disturb you.

Could you please tell me how to evaluate your Biomedicine/finance/law AdaptLLM models? I know maybe I can evaluate the benchmark PubMedQA with [lm-evaluation-harness](https://github.com/EleutherAI/lm-evaluation-harness/tree/main), but how to evaluate the other datasets like ChemProt, ConvFinQA, and so on?

Another questions is that it seems that there are some repetition in the datasets, such as the first three items in the test set of [ChemProt](https://huggingface.co/datasets/AdaptLLM/ChemProt/tree/main) shows:
![image](https://github.com/microsoft/LMOps/assets/166595333/3cf49c06-b93d-4219-9467-3040e38811a9)
The contents seem to be the same although they are not identical. Are they repetitions? Do we need to remove the repetition?

**Comment by cdxeve** [comment]
Hi,

**Regarding the evaluation**

You can implement the evaluation code using the lm-eval-harness framework. We have provided pre-templatized input instructions and output completions for each domain-specific task on Hugging Face:

[Biomedicine tasks](https://huggingface.co/datasets/AdaptLLM/medicine-tasks)
[Finance tasks](https://huggingface.co/datasets/AdaptLLM/finance-tasks)
[Law tasks](https://huggingface.co/datasets/AdaptLLM/law-tasks)

For multiple-choice tasks (including RCT, ChemProt, MQP, USMLE, PubMedQA, Headline, FPB, FiQA_SA, SCOTUS, CaseHold, UnfairToS), you can follow any multiple-choice task (e.g., SIQA) in lm-eval-harness. A helpful guideline is available [here](https://github.com/EleutherAI/lm-evaluation-harness/blob/main/docs/new_task_guide.md#multiple-choice-format).

For text completion tasks (including ConvFinQA, NER), you can follow the example of text completion tasks like SQuADv2.

**Regarding the repetition in the datasets**

Thank you for your careful review! The raw ChemProt dataset we used is from the [DAPT repository](https://github.com/allenai/dont-stop-pretraining/tree/master). We had not noticed this issue before, but the repetition is likely acceptable for our experiments. Therefore, you do not need to remove the repetitions.

**Comment by Amireux0000** [comment]
Can you please give me the full code you used to evaluate this model?

**Comment by Amireux0000** [comment]
> Dear authors, I'm reading your paper [Adapting Large Language Models via Reading Comprehension](https://huggingface.co/papers/2309.09530). I have some questions to disturb you.
> 
> Could you please tell me how to evaluate your Biomedicine/finance/law AdaptLLM models? I know maybe I can evaluate the benchmark PubMedQA with [lm-evaluation-harness](https://github.com/EleutherAI/lm-evaluation-harness/tree/main), but how to evaluate the other datasets like ChemProt, ConvFinQA, and so on?
> 
> Another questions is that it seems that there are some repetition in the datasets, such as the first three items in the test set of [ChemProt](https://huggingface.co/datasets/AdaptLLM/ChemProt/tree/main) shows: ![image](https://private-user-images.githubusercontent.com/166595333/331495642-3cf49c06-b93d-4219-9467-3040e38811a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODU1OTAsIm5iZiI6MTcxODc4NTI5MCwicGF0aCI6Ii8xNjY1OTUzMzMvMzMxNDk1NjQyLTNjZjQ5YzA2LWI5M2QtNDIxOS05NDY3LTMwNDBlMzg4MTFhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQwODIxMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTg5MzQwOGJmZmUyNzhlZmE2NDEwNWMyN2FiOTk4ZmQyNzkzNTBlNDcxNjlmZWIxNjcyNjk0ZmY1MTgxMGM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.195H_tRD5W8u-Ja2BK5cU4H9N4BWdZBzubRzVQYqLiA) The contents seem to be the same although they are not identical. Are they repetitions? Do we need to remove the repetition?

Hi!Can you please give me the full code you used to evaluate this model?

**Comment by cdxeve** [comment]
Hi, we are currently working on the next version of AdaptLLM at [Instruction-Pretrain](https://huggingface.co/instruction-pretrain/finance-Llama3-8B), with plans to release the evaluation code by then, please stay tuned.
