### ISSUE TITLE
A problem occur when execute the first procedure.

### ISSUE THREAD

**Issue by zhouchang123** [microsoft/LMOps#235]
![image](https://github.com/microsoft/LMOps/assets/61148892/f296dc63-6e11-454c-9a11-d4f482badb7d)

**Comment by zhouchang123** [comment]
![image](https://github.com/microsoft/LMOps/assets/61148892/6a4ac98c-7666-4347-846c-5eea22edd864)

**Comment by zhouchang123** [comment]
I just execute the order :
python DPR/generate_dense_embeddings.py \
	 model_file=${RETRIEVER} \
	 ctx_src=dpr_uprise shard_id=0 num_shards=1 \
	 out_file=$PWD/my_data/experiment/uprise/dpr_enc_index \
	 ctx_sources.dpr_uprise.prompt_pool_path=${PROMPT_POOL} \
	 ctx_sources.dpr_uprise.prompt_setup_type=qa \
	 encoder.cache_dir=${CACHE_DIR} \
	 hydra.run.dir=$PWD/my_data/experiment/uprise
THEN THE PROBLEM OCCURED

**Comment by zhouchang123** [comment]
after modify output = results[i] to output=result.get(i)
a new problem occur
![image](https://github.com/microsoft/LMOps/assets/61148892/1dd9fc6c-64dc-460b-a25c-d94cfe3b06bf)

**Comment by cdxeve** [comment]
There seems to be an issue with parallel execution. How about restricting the CUDA devices to 1? Try running the following command:

```bash
export RETRIEVER=[DOWNLOADED_CKPT_PATH] # path to the downloaded retriever checkpoint
export PROMPT_POOL=[DOWNLOADED_POOL_PATH] # path to the downloaded prompt pool
export CACHE_DIR=[CAHCHE_DIR] # directory path for caching the LLM checkpoints, task datasets, etc.

CUDA_VISIBLE_DEVICES='0' python DPR/generate_dense_embeddings.py \
	 model_file=${RETRIEVER} \
	 ctx_src=dpr_uprise shard_id=0 num_shards=1 \
	 out_file=$PWD/my_data/experiment/uprise/dpr_enc_index \
	 ctx_sources.dpr_uprise.prompt_pool_path=${PROMPT_POOL} \
	 ctx_sources.dpr_uprise.prompt_setup_type=qa \
	 encoder.cache_dir=${CACHE_DIR} \
	 hydra.run.dir=$PWD/my_data/experiment/uprise
```

**Comment by zhouchang123** [comment]
The problem seems has been solved,but where the result saved?

**Comment by cdxeve** [comment]
Could you please show me the log in your terminal when you finished the first execution?

**Comment by zhouchang123** [comment]
![image](https://github.com/microsoft/LMOps/assets/61148892/be53772f-ed57-4fe2-9237-a7e2960ad71d)
I set CUDA_VISIBLE_DEVICES='2' but it still run on cuda'0'

**Comment by cdxeve** [comment]
Sometimes running the same command multiple times can lead to such errors. How about first removing the file folder and then rerunning the command:

1. Remove the existing folder:
   ```bash
   rm -r $PWD/my_data/experiment/uprise/
   ```

2. Run the following command:
   ```bash
   export RETRIEVER=[DOWNLOADED_CKPT_PATH] # Path to the downloaded retriever checkpoint
   export PROMPT_POOL=[DOWNLOADED_POOL_PATH] # Path to the downloaded prompt pool
   export CACHE_DIR=[CACHE_DIR] # Directory path for caching the LLM checkpoints, task datasets, etc.

   CUDA_VISIBLE_DEVICES='0' python DPR/generate_dense_embeddings.py \
     model_file=${RETRIEVER} \
     ctx_src=dpr_uprise shard_id=0 num_shards=1 \
     out_file=$PWD/my_data/experiment/uprise/dpr_enc_index \
     ctx_sources.dpr_uprise.prompt_pool_path=${PROMPT_POOL} \
     ctx_sources.dpr_uprise.prompt_setup_type=qa \
     encoder.cache_dir=${CACHE_DIR} \
     hydra.run.dir=$PWD/my_data/experiment/uprise
   ```

**Comment by zhouchang123** [comment]
Thank you very much.But it still doesn't work,the dpr_enc_index folder remains non-exist.

**Comment by zhouchang123** [comment]
Here is the override config file.
![Uploading image.png…]()

**Comment by cdxeve** [comment]
This is weird. I don't think the execution finished successfully. The log should end with writing information (`Total passages processed %d. Written to %s`) rather than printing out the tensor (`Producing encodings for passages range: %d to %d (out of total %d`). See [uprise/DPR/generate_dense_embeddings.py](https://github.com/microsoft/LMOps/blob/bd0bf742187423f360309aa48345e323e1c0d0f8/uprise/DPR/generate_dense_embeddings.py#L153).

<img width="831" alt="image" src="https://github.com/microsoft/LMOps/assets/26034310/d5562376-c20d-42cc-a225-03387ba51ed1">

Please check if the function `gen_ctx_vectors()` executes successfully by adding some breakpoints like `pdb` or `print`.

**Comment by zhouchang123** [comment]
I found the error, that's because I forgot to delete the code that I add when debug.
Thank you very much.
