### ISSUE TITLE
[UPRISE]CUDA out of memory. Tried to allocate 3.25 GiB. GPU

### ISSUE THREAD

**Issue by zhouchang123** [microsoft/LMOps#237]
When run the code:bash inference.sh,it occurs an error.
![image](https://github.com/microsoft/LMOps/assets/61148892/fa43a14f-e8c0-4dbe-a8e9-06556c0a3384)
![image](https://github.com/microsoft/LMOps/assets/61148892/b2ab0790-2844-48a6-8ab9-7740cf962df0)

**Comment by zhouchang123** [comment]
I use `gpustat -i 1 ` to watch the gpu state .
When it went wrong ,the gpu 2 and 3 were not on the limit ,only 0 went out of memory.(My friend is using 1)
How to solve it? 
![image](https://github.com/microsoft/LMOps/assets/61148892/41c972f7-e675-49ce-833c-f7d3a300f130)

**Comment by cdxeve** [comment]
1. Try reducing  the inference batch_size to 4 or even lower: 
<img width="711" alt="image" src="https://github.com/microsoft/LMOps/assets/26034310/4dae7301-82f5-426a-8eb4-a5c39475e4e2">

 2. add CUDA_VISIBLE_DEVICES='0,2' if necessary.

**Comment by zhouchang123** [comment]
Yes,it works. But it still shows that the use memory on gpu 0 is double of gpu 2

**Comment by cdxeve** [comment]
This is okay, sometimes the model can load unevenly across different GPUs.
