### ISSUE TITLE
[UPRISE}When use llm to score the prompt,the connection stopped.

### ISSUE THREAD

**Issue by zhouchang123** [microsoft/LMOps#245]
When use llm to score the prompt,the connection stopped.Thus the files are not complete.
Can I operate a new same order to continue score the prompts?
![image](https://github.com/user-attachments/assets/b99c3c86-753f-4463-8e9a-14993aa91188)

**Comment by zhouchang123** [comment]
![image](https://github.com/user-attachments/assets/8bf443f5-7e73-4b67-b637-9471b8f96a3c)
When load piqa dataset ,a problem happened.

**Comment by cdxeve** [comment]
try `pip install --upgrade datasets`? And it seems that the huggingface official `piqa` dataset has been removed, you may download [this one](https://huggingface.co/datasets/ybisk/piqa).

**Comment by zhouchang123** [comment]
Do you mean download the file to local and download from remote like this?
![image](https://github.com/user-attachments/assets/9af17278-2aff-4eb6-ac13-a7ffc196608f)

**Comment by cdxeve** [comment]
Both are okay. Please read the official documentation for detailed instructions.
