### ISSUE TITLE
Training code unable to find for AdaptLLM

### ISSUE THREAD

**Issue by chowkamlee81** [microsoft/LMOps#258]
For AdaptLLM, where we can find training code. Only inference codes are provided

**Comment by cdxeve** [comment]
Thanks for the question. We've provided code in the adaptllm repo to convert raw corpora into a reading comprehension format. After that, you’ll need to mix the converted data with general instructions from [OpenOrca](https://huggingface.co/datasets/Open-Orca/OpenOrca) at a 1:1 ratio (counted by tokens). 

Except for the pre-training data, our pre-training process is the same as the vanilla pre-training of language models. You may refer to our [pre-training suggestions](https://huggingface.co/instruction-pretrain/instruction-synthesizer) or [this issue](https://github.com/microsoft/LMOps/issues/257) for more details.
