### ISSUE TITLE
[MiniLLM] The "processed_data.tar" data link is invalid.

### ISSUE THREAD

**Issue by shhn1** [microsoft/LMOps#263]
I used the code in the guide to download the data, but found that the URL was no longer valid. 
`DLINK=$(echo -n "aHR0cHM6Ly9jb252ZXJzYXRpb25odWIuYmxvYi5jb3JlLndpbmRvd3MubmV0L2JlaXQtc2hhcmUtcHVibGljL01pbmlMTE0vcHJvY2Vzc2VkX2RhdGEudGFyP3N2PTIwMjMtMDEtMDMmc3Q9MjAyNC0wNC0xMFQxMyUzQTExJTNBNDRaJnNlPTIwNTAtMDQtMTFUMTMlM0ExMSUzQTAwWiZzcj1jJnNwPXImc2lnPTRjWEpJalZSWkhJQldxSGpQZ0RuJTJGMDFvY3pwRFdYaXBtUENVazNaOHZiUSUzRA==" | base64 --decode)
wget -O processed_data.tar $DLINK`

I also tried to open the URL `https://conversationhub.blob.core.windows.net/,` but found that the URL could not be opened either.

On August 16, I could still open it, but when I wanted to download precess_data.tar now, I found that the link was invalid and could not be opened.

Is there any other way to get process_data.tar? Looking forward to your reply!  : )

**Comment by aaab8b** [comment]
me too. it shows "403 Key based authentication is not permitted on this storage account."

**Comment by donglixp** [comment]
The links have been fixed. (https://github.com/microsoft/LMOps/blob/main/minillm/README.md)

@aaab8b @shhn1
