### ISSUE TITLE
[MiniLLM]没有看出kd和seqkd的loss的区别

### ISSUE THREAD

**Issue by lean-wang** [microsoft/LMOps#266]
老师您好，想问问这二者有什么区别，从您的代码的角度，两者都是token级别的klloss，seqkd没有看到整个句子的联合概率连乘啊,还是我的理解有误

**Comment by HoyTiger** [comment]
俺也没看出来

**Comment by t1101675** [comment]
kd 和 seqkd 的主要区别可以看这篇论文 https://arxiv.org/pdf/1606.07947 （kd 为此论文中的word-kd）

**Comment by aaab8b** [comment]
> kd 和 seqkd 的主要区别可以看这篇论文 https://arxiv.org/pdf/1606.07947 （kd 为此论文中的word-kd）

hi yuxian, can you look at the other issue we talk about, the availability of all data and minillm models?

**Comment by lean-wang** [comment]
谢谢老师

**Comment by t1101675** [comment]
> > kd 和 seqkd 的主要区别可以看这篇论文 https://arxiv.org/pdf/1606.07947 （kd 为此论文中的word-kd）
> 
> hi yuxian, can you look at the other issue we talk about, the availability of all data and minillm models?

Hi, the storage of our server is updating, so the link is temporarily unavailable. We will fix this recently. Sorry for the trouble.

**Comment by aaab8b** [comment]
> > > kd 和 seqkd 的主要区别可以看这篇论文 https://arxiv.org/pdf/1606.07947 （kd 为此论文中的word-kd）
> > 
> > 
> > hi yuxian, can you look at the other issue we talk about, the availability of all data and minillm models?
> 
> Hi, the storage of our server is updating, so the link is temporarily unavailable. We will fix this in these days. Sorry for the trouble.

thanks for the reply. Is there any certain date I can count on?

**Comment by t1101675** [comment]
The link is now available~
