### ISSUE TITLE
[Question] sampler.py in case of args.teacher_mixed_alpha

### ISSUE THREAD

**Issue by kykim0** [microsoft/LMOps#267]
Hello,

Thanks for your code contribution!

I wanted to ask a quick question about the `run_sample` method in sampler.py to make sure I'm not misreading it. IIUC, the method is generating samples either from the teacher-mixed or the student distribution prior to training depending on whether or not `args.teacher_mixed_alpha` is set.

Lines 68-99 seem to be this implementation, and the block that starts from line 83 appears to be handling the case of sampling from the student (and not the mixed) distribution. If so, shouldn't the if-statement be `if self.args.teacher_mixed_alpha is None` rather than not None? Perhaps I'm missing something, but I'd appreciate it if you could clarify this part of the code. Thanks!

**Comment by t1101675** [comment]
Hi, thanks for your attention to our work!
It is true that we set `args.teacher_mixed_alpha` to use the teacher-mixed sampling but the implementation is in the function `generate` starting from this [line](https://github.com/microsoft/LMOps/blob/1d6ca760f2f8b712d85bdefae67518c140b8a4a5/minillm/transformers/src/transformers/generation/utils.py#L1435), which is triggered from this [line](https://github.com/microsoft/LMOps/blob/1d6ca760f2f8b712d85bdefae67518c140b8a4a5/minillm/minillm/sampler.py#L70) by calling `self.trainer.generate`.

Lines 83-99 in `run_sample.py` generates the responses from the student model, with is used to **compute the reverse KLD for monitoring the training process**, not the teacher-mixed generation. The teacher-mixed generation is obtained from [line 70](https://github.com/microsoft/LMOps/blob/1d6ca760f2f8b712d85bdefae67518c140b8a4a5/minillm/minillm/sampler.py#L70).

**Comment by kykim0** [comment]
That clarified things a lot, thank you for your response!
