### ISSUE TITLE
Could you provide the ROBERTA training corpus in MiniLLM?

### ISSUE THREAD

**Issue by Artexety** [microsoft/LMOps#33]
Could you please let me know if it is possible to share the dataset? If so, I would greatly appreciate it if you could provide me with information on where I can find it. Currently it is missing in the data.tar archive. Thank you!

**Comment by AboveParadise** [comment]
I've got the same problem, could you tell me where you found it? Thanks.

**Comment by AKaubay** [comment]
Hello, I also have the same problem. They gave the link to the four different datasets that compose RoBERTa but didn't give the script that preprocesses it.
