### ISSUE TITLE
Can you provide OpenLLaMA weights?

### ISSUE THREAD

**Issue by razor08** [microsoft/LMOps#34]
Hi,

Can you provide OpenLLaMA weights with the same settings that this paper has ran on the original LLaMA. Asking because LLaMA has a restrictive license usage.

Thanks.

**Comment by donglixp** [comment]
@razor08  Could you clarify which paper is for the issue?

**Comment by razor08** [comment]
Oh shoot. Should have specified that. Sorry :\

It's for this paper: [Knowledge Distillation of Large Language Models](https://arxiv.org/pdf/2306.08543.pdf)

On a side note: I found this paper very interesting in the sense that generation can be severely downgraded by quantization like techniques. Really interesting work 💯

**Comment by razor08** [comment]
Also, I am trying to run the LLaMA-7B model as provided in folder: `train/minillm/7B-init-13B-sft`

using the following code: 


```
from transformers import LlamaForCausalLM, LlamaTokenizer

tokenizer = LlamaTokenizer.from_pretrained(model_path)

model = LlamaForCausalLM.from_pretrained(model_path).to('cuda')
```

This is causing the kernel to be stopped. If I use the `AutoModelForCausalLM` class as used in the repo, it stops my instance directly.  Not sure what is causing this. Any suggestions? 

Side note: It would  be very helpful if an example notebook can be provided that uses Colab to make some generations with MiniLLM models. (that can fit into Colab GPU memory)

I am using an A10G Instance with 24GB VRAM.

**Comment by t1101675** [comment]
@razor08  Can you provide some error information?

**Comment by razor08** [comment]
When I run: 
```
model = LlamaForCausalLM.from_pretrained(model_path).to('cuda')
````

I get this error outputted on the cell in Jupyter notebook along with an error message stating the kernel is not running anymore. 
```---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
Cell In[4], line 1
----> 1 model = LlamaForCausalLM.from_pretrained(model_path).to('cuda')

File ~/llm/lib/python3.9/site-packages/transformers/modeling_utils.py:2604, in PreTrainedModel.from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
   2601 if from_pt:
   2602     if not is_sharded and state_dict is None:
   2603         # Time to load the checkpoint
-> 2604         state_dict = load_state_dict(resolved_archive_file)
   2606     # set dtype to instantiate the model under:
   2607     # 1. If torch_dtype is not None, we use that dtype
   2608     # 2. If torch_dtype is "auto", we auto-detect dtype from the loaded state_dict, by checking its first
   2609     #    weights entry that is of a floating type - we assume all floating dtype weights are of the same dtype
   2610     # we also may have config.torch_dtype available, but we won't rely on it till v5
   2611     dtype_orig = None

File ~/llm/lib/python3.9/site-packages/transformers/modeling_utils.py:463, in load_state_dict(checkpoint_file)
    461     return safe_load_file(checkpoint_file)
    462 try:
--> 463     return torch.load(checkpoint_file, map_location="cpu")
    464 except Exception as e:
    465     try:

File ~/llm/lib/python3.9/site-packages/torch/serialization.py:809, in load(f, map_location, pickle_module, weights_only, **pickle_load_args)
    807             except RuntimeError as e:
    808                 raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None
--> 809         return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
    810 if weights_only:
    811     try:

File ~/llm/lib/python3.9/site-packages/torch/serialization.py:1172, in _load(zip_file, map_location, pickle_module, pickle_file, **pickle_load_args)
   1170 unpickler = UnpicklerWrapper(data_file, **pickle_load_args)
   1171 unpickler.persistent_load = persistent_load
-> 1172 result = unpickler.load()
   1174 torch._utils._validate_loaded_sparse_tensors()
   1176 return result

File ~/llm/lib/python3.9/site-packages/torch/serialization.py:1142, in _load.<locals>.persistent_load(saved_id)
   1140 else:
   1141     nbytes = numel * torch._utils._element_size(dtype)
-> 1142     typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
   1144 return typed_storage

File ~/llm/lib/python3.9/site-packages/torch/serialization.py:1112, in _load.<locals>.load_tensor(dtype, numel, key, location)
   1109 def load_tensor(dtype, numel, key, location):
   1110     name = f'data/{key}'
-> 1112     storage = zip_file.get_storage_from_record(name, numel, torch.UntypedStorage)._typed_storage()._untyped_storage
   1113     # TODO: Once we decide to break serialization FC, we can
   1114     # stop wrapping with TypedStorage
   1115     typed_storage = torch.storage.TypedStorage(
   1116         wrap_storage=restore_location(storage, location),
   1117         dtype=dtype,
   1118         _internal=True)

KeyboardInterrupt: ```

Get the same error when I run line 3 below: 

```
model_name = "/home/jovyan/minillm-llama-7b"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name).to(device)
```

PyTorch Version: torch-2.0.1-cp311
Deepspeed Version: deepspeed-0.9.5

I am running this on an A10G GPU with 24GB VRAM.

**Comment by t1101675** [comment]
Can you load the [original llama checkpoints](https://huggingface.co/decapoda-research/llama-7b-hf) successfully? It is probably because the VRAM is not large enough.

**Comment by razor08** [comment]
Yes I can. I can load LLaMA and OpenLLaMA checkpoints successfully. 
I am using 7B checkpoints which is roughly 16-17GB and the GPU VRAM is 24GB. 
Can you provide a sample notebook like on Colab or something? That will be very helpful. Thanks!

**Comment by t1101675** [comment]
I load `minillm-llama-7b` successfully using the code 
```bash
model_name = "minillm-llama-7b"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name).to(device)
```
I think it is probably because we store the whole checkpoint in one file, and LLaMA stores the checkpoints in multiple files. It seems that loading a large file requires more memory footprint than loading multiple files (see this [link](https://github.com/huggingface/transformers/issues/13548)). 
We plan to split the checkpoints into multiple shards as LLaMA does. Before that, you can try some loading arguments that reduce the CPU memory usage like:
```bash
model_name = "minillm-llama-7b"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name, low_cpu_mem_usage=True, max_memory={"cpu": "24GiB"}).to(device)
```
See this [link](https://huggingface.co/docs/transformers/v4.30.0/en/main_classes/model#large-model-loading) for more information.

**Comment by razor08** [comment]
I tried this but it did not work :/ 

Not sure what is causing this... I guess I will wait till its split into shards. 
Just one suggestion: If you train this on OpenLLaMA, it will be available to use for all purposes since it is on an Apache-2.0 license and then you can even make it available on HF (not sure if this is in scope for you folks but I just thought I'll share my thoughts). Your research looks very interesting! Good luck! 
Thanks!
(Feel free to close this issue.)

**Comment by t1101675** [comment]
Thanks for your suggestion! We will split the shards as soon as possible.
