### ISSUE TITLE
A Environment Bug in miniLLM

### ISSUE THREAD

**Issue by ViktorAxelsen** [microsoft/LMOps#41]
In minillm, there is something wrong with the given environment. 
The deepspeed==0.8.0 will make pydantic==2.0+ installed in the same time. 
But in this combination of version, a naive code 'import deepspeed' fails.
I must change the version of pydantic to 1.10.11, then it seems ok.

**Comment by t1101675** [comment]
It seems that pydantic has updated to 2.0+ recently but deepspeed==0.8.0 only supports 1.10.x. The environment has been updated.

**Comment by donglixp** [comment]
@ViktorAxelsen  Does the above solution work?

**Comment by ViktorAxelsen** [comment]
> @ViktorAxelsen Does the above solution work?

Yes, thanks.
