### ISSUE TITLE
modeling_xgml.py

### ISSUE THREAD

**Issue by amurtadha** [microsoft/LMOps#43]
can you please modify modeling_xgml.py . In such way, we can you your code with huggingface. Thank you

**Comment by donglixp** [comment]
@amurtadha Do you mean the file `minillm/transformers/src/transformers/models/xglm/modeling_xglm.py`?

**Comment by t1101675** [comment]
@amurtadha Do you mean updating `minillm/transformers/src/transformers/models/xglm/modeling_xglm.py` to the latest version? Or adding TensorParallel to `modeling_xglm.py`?

By the way, TensorParallel is only required by > 7B models. The original HuggingFace code base works well for smaller models.

**Comment by amurtadha** [comment]
@donglixp @t1101675 I mean : transformers.models.xglm.modeling_xglm of huggingface

**Comment by amurtadha** [comment]
@t1101675 @donglixp Actually, I am talking about the implementation of Structured Prompting 
:  https://github.com/microsoft/LMOps/tree/main/structured_prompting/hf-version  
I would like  to update the scaled attention of transformers.models.xglm.modeling_xglm 
thank you

**Comment by donglixp** [comment]
https://github.com/microsoft/LMOps/issues/47
