### ISSUE TITLE
The LLMA method seems not support batch decoding.

### ISSUE THREAD

**Issue by rangehow** [microsoft/LMOps#46]
We know that when the batch size increases, it benefits from the powerful parallel capabilities of the GPU, and the speedup is often significantly larger than the 2-3X acceleration mentioned in the llma readme. So, I am quite curious whether I have misunderstood something about this source code. 

> It seems that if we apply the llma algorithm in batch form, the actual step length for each sentence at each time step varies, making it impossible to form a tensor properly. 
```[tasklist]
### Tasks
```

**Comment by nyanyanya** [comment]
> We know that when the batch size increases, it benefits from the powerful parallel capabilities of the GPU, and the speedup is often significantly larger than the 2-3X acceleration mentioned in the llma readme. So, I am quite curious whether I have misunderstood something about this source code.
> 
> > It seems that if we apply the llma algorithm in batch form, the actual step length for each sentence at each time step varies, making it impossible to form a tensor properly.


@rangehow, the code here doesn't implement batch inference, but the algorithm can also work with batch. There will be holes in the kv_cache, and care should be take into consideration to guarantee attention mask, position ids etc work correctly. The steps required to finish the batch is the maximum of the steps required to finish each sample without the batch. The speed-up will be less with batch inference, and the actual gain depends on your implementation.

**Comment by nyanyanya** [comment]
> Good job !
> 
> I also want to know whether we can use openai api to implement decode process, which do not implement in source code.

Unfortunately it can't work with APIs.
