### ISSUE TITLE
Code issues on running MiniLLM 

### ISSUE THREAD

**Issue by jongwooko** [microsoft/LMOps#57]
First of all, thank you for sharing your codes. 

When I tried to run sft and kd on gpt2, it works.
However, when I tried to run minillm, I encounter two problems.

1. The first problem is that 
```
  File "/home/work/kd/minillm/minillm/pipelines.py", line 82, in collate
    no_model_batch["full_ids"][:len(full_ids)-1] = torch.tensor(full_ids[:-1], dtype=torch.long)
RuntimeError: The expanded size of the tensor (512) must match the existing size (60) at non-singleton dimension 1.  Target sizes: [16, 512].  Tensor sizes: [60]
``` 

In my thought the line 82-84 should be change from

```
no_model_batch["full_ids"][:len(full_ids)-1] = torch.tensor(full_ids[:-1], dtype=torch.long)
no_model_batch["full_attention_mask"][:len(full_ids)-1] = 1.0
no_model_batch["full_label_ids"][len(prompt)-1:len(full_ids)-1] = torch.tensor(response, dtype=torch.long)
``` 

to 

```
no_model_batch["full_ids"][i][:len(full_ids)-1] = torch.tensor(full_ids[:-1], dtype=torch.long)
no_model_batch["full_attention_mask"][i][:len(full_ids)-1] = 1.0
no_model_batch["full_label_ids"][i][len(prompt)-1:len(full_ids)-1] = torch.tensor(response, dtype=torch.long)
``` 
.

2. The second problem is that

It seems there are two type of preprocessed dolly datasets, full and propmt.
Full dataset is used for sft and kd and prompt dataset is used for minillm.

However, when I run  
```
bash scripts/gpt2/tools/process_data_dolly.sh 
``` 

It only returns one type of preprocessed dolly.
therefore, when I run the minillm, I have another errors that 

```
File ".//train_minillm.py", line 85, in main
    assert len(data) <= self.max_prompt_length
AssertionError
    train(
  File "/home/work/kd/minillm/minillm/__init__.py", line 37, in train
    sampler.run_sample(args.num_rollouts)
  File "/home/work/kd/minillm/minillm/sampler.py", line 47, in run_sample
    batch: PromptBatch = next(self.pipeline_iterator)
``` 

could you please check the problem and give some solution? 

Thank you.

**Comment by t1101675** [comment]
Hi, thank you for your attention to our work!

For the first issue, I think `[i]` indeed should be added. In our experiments, we only use the `prompt` type of dolly dataset (as stated in the second issue), which does not cause these lines to execute. I think that's the reason why I miss the bug.

For the second issue, you can enable the prompt version by setting `--only-prompt` in the data processing [file](https://github.com/microsoft/LMOps/blob/main/minillm/scripts/llama/tools/process_data_dolly.sh), which is used for MiniLLM. The two code blocks in the file are examples of processing these two data types. It seems I mistakenly set the output directories to the same path. You can fix this by setting them to different paths like `xxx/dolly_prompt` and `xxx/dolly_full`. 

Thanks for pointing out these issues, I will them in the next version of code.
