### ISSUE TITLE
Dataset and training code ?

### ISSUE THREAD

**Issue by marson666** [microsoft/LMOps#6]
Hi, thanks for you great work about "Promptist: reinforcement learning for automatic prompt optimization".

Will you release the dataset the paper mentioned in the paper and the training code?

**Comment by ming1523** [comment]
same here. looking forward the release of optimizing prompts for text to image generation

**Comment by amritkumar9595** [comment]
yup ! me as well ! waiting for the release of  promptist code

**Comment by dkkim93** [comment]
+1 :) The release of the dataset used in the paper will be really helpful! Thank you for the great work!

**Comment by donglixp** [comment]
@YRdddream

**Comment by YRdddream** [comment]
We have released the source code of Promptist.

**Comment by dkkim93** [comment]
Thank you for uploading the Promptist code! It is very helpful 👍 
I would like to reproduce the results by training Promptist on our server. 
Would it be possible to additionally share the training dataset (i.e., 360K data in Section 3.1) and the supervised fine-tuned GPT model?
Thank you again for your great work!

**Comment by YRdddream** [comment]
We have released the data at https://drive.google.com/file/d/1EsuYEb9BuinJCdzvQ_gqa_Gu_sTyLWbf/view?usp=drive_link.
