### ISSUE TITLE
how to import the customized transformers

### ISSUE THREAD

**Issue by 614TChen** [microsoft/LMOps#64]
i wonder how i can import from the local transformers folder. i seems the installed transformers will be considered priorly as i can not import module like ParallelLlamaForCausalLM.

**Comment by donglixp** [comment]
@614TChen Could you be more specific about which work you are trying?

**Comment by 614TChen** [comment]
thank you for you quick reply. i'm working with minillm. it seems i have just solved the problem by extending the sys path so i will closed the issue
