### ISSUE TITLE
Distillation between two different LLM

### ISSUE THREAD

**Issue by 614TChen** [microsoft/LMOps#66]
Hi, just wonder if it is possible to do distillation between two model with different tokenizers. the two tokenizers can be different in vocabulary size or have tokens in different position.

**Comment by t1101675** [comment]
Distillation between two models with different vocabularies is not supported in the current MiniLLM method. Maybe we will address this limitation in future work. Any ideas/suggestions are welcome!

**Comment by haiduo** [comment]
> Hi, just wonder if it is possible to do distillation between two model with different tokenizers. the two tokenizers can be different in vocabulary size or have tokens in different position.

you can try it. [Towards Cross-Tokenizer Distillation](https://github.com/Nicolas-BZRD/llm-recipel)
