### ISSUE TITLE
Why Can GPT Learn In-Context? Language Models Secretly Perform Gradient Descent as Meta-Optimizers

### ISSUE THREAD

**Issue by naokishibuya** [microsoft/LMOps#7]
Hi,

Thanks for the outstanding paper "Why Can GPT Learn In-Context?".

I don't know if this is the right place to talk about this, but I might've found a typo in the paper and want to let you know about it.

In equation (8), you have the transpose as in ${x'_i}^\top$. 

However, you have the outer product symbol $\otimes$, which by definition, handles the transpose.

So, the transpose operation is only necessary if you mean the outer product symbol is matrix multiplication. Otherwise, removing the outer product symbol may be better, as it is eventually done in equation (9).

I hope it's helpful to you.

**Comment by donglixp** [comment]
Hi @naokishibuya ,

Thanks for your suggestion! We will fix it in the paper.
