### ISSUE TITLE
TypeError: 'Loss.pt_loss() missing 1 required positional argument: 'logits'

### ISSUE THREAD

**Issue by wwtx9** [microsoft/LMOps#88]
It appears there is a bug in the source code related to a TypeError: 'Loss.pt_loss() missing 1 required positional argument: 'logits'' within the 'evaluate_pt' function in 'trainer.py'. Would it be possible to have any suggestion on that? Thank you!

**Comment by t1101675** [comment]
Thanks for reporting! We have fixed this issue. #86 #87

**Comment by t1101675** [comment]
I think for most of the experiments (student model < 7B), 4*80G is enough. For the largest scale experiments (13B->7B), maybe more devices are needed, or you can use some techniques like zero-3/LoRA to reduce the memory usage.
